In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import patsy
import statsmodels.api as sm
from scipy.stats import ttest_ind


In [5]:
df= pd.read_csv("exportS-4_comma.csv")

In [6]:
df


Type       Name  Number    Year  \
0       Site  Kastrouli     NaN     NaN   
1       Area          A     NaN  2016.0   
2      Locus        NaN     NaN     NaN   
3     Basket        NaN     NaN     NaN   
4       Bulk        NaN     NaN     NaN   
5       Bulk        NaN     NaN     NaN   
6       Bulk        NaN     NaN     NaN   
7       Bulk        NaN     NaN     NaN   
8     Basket        NaN     NaN     NaN   
9       Bulk        NaN     NaN     NaN   
10      Bulk        NaN     NaN     NaN   
11      Bulk        NaN     NaN     NaN   
12      Bulk        NaN     NaN     NaN   
13      Bulk        NaN     NaN     NaN   
14      Bulk        NaN     NaN     NaN   
15      Bulk        NaN     NaN     NaN   
16      Bulk        NaN     NaN     NaN   
17     Locus        NaN     NaN     NaN   
18    Basket        NaN     NaN     NaN   
19      Bulk        NaN     NaN     NaN   
20    Basket        NaN     NaN     NaN   
21      Bulk        NaN     NaN     NaN   
22      Bulk        NaN     NaN     NaN   
23      Bulk        NaN     NaN     NaN   
24      Bulk        NaN     NaN     NaN   
25      Bulk        NaN     NaN     NaN   
26      Bulk        NaN     NaN     NaN   
27      Bulk        NaN     NaN     NaN   
28     Locus        NaN     NaN     NaN   
29    Basket        NaN     NaN     NaN   
...      ...        ...     ...     ...   
1093    Bulk        NaN     NaN     NaN   
1094    Bulk        NaN     NaN     NaN   
1095    Bulk        NaN     NaN     NaN   
1096    Bulk        NaN     NaN     NaN   
1097    Bulk        NaN     NaN     NaN   
1098    Bulk        NaN     NaN     NaN   
1099    Bulk        NaN     NaN     NaN   
1100    Bulk        NaN     NaN     NaN   
1101    Bulk        NaN     NaN     NaN   
1102    Bulk        NaN     NaN     NaN   
1103    Bulk        NaN     NaN     NaN   
1104    Bulk        NaN     NaN     NaN   
1105    Bulk        NaN     NaN     NaN   
1106    Bulk        NaN     NaN     NaN   
1107    Bulk        NaN     NaN     NaN   
1108    Bulk        NaN     NaN     NaN   
1109    Bulk        NaN     NaN     NaN   
1110    Bulk        NaN     NaN     NaN   
1111    Bulk        NaN     NaN     NaN   
1112    Bulk        NaN     NaN     NaN   
1113    Bulk        NaN     NaN     NaN   
1114    Bulk        NaN     NaN     NaN   
1115    Bulk        NaN     NaN     NaN   
1116    Bulk        NaN     NaN     NaN   
1117    Bulk        NaN     NaN     NaN   
1118    Bulk        NaN     NaN     NaN   
1119    Bulk        NaN     NaN     NaN   
1120    Bulk        NaN     NaN     NaN   
1121    Bulk        NaN     NaN     NaN   
1122    Bulk        NaN     NaN     NaN   

                                            Description  Locus Number  \
0                                                   NaN           NaN   
1                                          Looted tombs           NaN   
2                                 Cleaning looted tombs           NaN   
3                                      Sieve collection         100.0   
4     2 Mycenaean handles; 1 Mycenaean chalice paint...           NaN   
5     bulk from original basket 20000, rom the one w...           NaN   
6     27 sheep/goat fragments; 1 talus; 1 sheep/goat...           NaN   
7     1 sheep/phalange, 2 large unidentified sheep/g...           NaN   
8                    Special pottery, Mycenaean pot rim         100.0   
9                     Mycenaean cup rim linear ornament           NaN   
10                    Mycenaean cup rim linear ornament           NaN   
11    2 Mycenaean handles; 1 Mycenaean chalice paint...           NaN   
12             Mycenaean cup rim, black with brown band           NaN   
13                                             cup base           NaN   
14    bulk from original basket 20000, rom the one w...           NaN   
15    Diagnostic pottery, 2 rims; 1 cross section ov...           NaN   
16    27 sheep/goat fragments; 1 talus; 1 sheep/goat...           NaN   
17                   Cleani

In [12]:
list(df)

['Type',
 'Name',
 'Number',
 'Year',
 'Description',
 'Locus Number',
 'Area Name',
 'Site Name',
 'Geom',
 'D Code',
 'Id String',
 'Basket Barcode',
 'Crate Number',
 'Location',
 'Square',
 'Date',
 'Total Count',
 'Total Weight',
 'Length',
 'Width',
 'Thickness',
 'Kind',
 'Northing',
 'Easting',
 'Latitude',
 'Longitude',
 'Elevation',
 'Srid',
 'Link Name',
 'Other Names',
 'Number.1',
 'Major Periods',
 'Other Periods',
 'Surveyors',
 'Excavation Institution',
 'Permit Number',
 'Publication Bibliography',
 'Collection Strategy',
 'Paleolithic',
 'Natufian',
 'Neo',
 'Ppn',
 'Ppna',
 'Ppnbc',
 'Pn',
 'Prehistoric',
 'Chal',
 'Eb',
 'Eb1',
 'Eb23',
 'Ib',
 'Mb',
 'Mb2a',
 'Mb2bc',
 'Lb',
 'Ia',
 'Ia1',
 'Ia2',
 'Ia3',
 'Classical',
 'Hel',
 'Rom',
 'Erom',
 'Lrom',
 'Byz',
 'Ebyz',
 'Lbyz',
 'Islamic',
 'Ei',
 'Mi1',
 'Mi23',
 'Li',
 'Mandate Modern',
 'Comments']

In [10]:
df['Type'].unique()

array(['Site', 'Area', 'Locus', 'Basket', 'Bulk'], dtype=object)

In [11]:
df['Name'].unique()

array(['Kastrouli', 'A', nan], dtype=object)

In [13]:
df['Number'].unique()


array([ nan])

In [14]:
df['Year'].unique()


array([   nan,  2016.])

In [15]:
df['Description'].unique()

array([nan, 'Looted tombs', 'Cleaning looted tombs', 'Sieve collection',
       '2 Mycenaean handles; 1 Mycenaean chalice painted; 1 fenestrated vessel; 3 handles; 58 coarseware body sherds; 322 fineware body sherds; 3 rims; 7 lug handles; 5 coarse rims; 1 fine base; 2 coarse bases; 14 painted fine rims; 6 painted body sherds; 1 base',
       'bulk from original basket 20000, rom the one with 400+ count',
       '27 sheep/goat fragments; 1 talus; 1 sheep/goat; 1 sheep/goat phalange; 1 bird bone',
       '1 sheep/phalange, 2 large unidentified sheep/goat bones, 15 unidentified bone fragments',
       'Special pottery, Mycenaean pot rim',
       'Mycenaean cup rim linear ornament',
       'Mycenaean cup rim, black with brown band', 'cup base',
       'Diagnostic pottery, 2 rims; 1 cross section oval handle; 1 handle root; 5 fineware sherds',
       'Cleaning south end of lintel stone',
       'Sieve collection from locus 102', 'assorted unanalyzed sherds',
       'Bulk pottery from locus

In [16]:
df['Locus Number'].unique()

array([  nan,  100.,  102.,  104.,  106.,  107.,  108.,  105.,  110.,
        109.,  111.,  115.,  113.,  112.,  114.,  117.,  118.,  119.,
        120.,  121.,    0.])

In [17]:
df['Area Name'].unique()

array([nan, 'A'], dtype=object)

In [18]:
df['Site Name'].unique()

array([nan, 'Kastrouli'], dtype=object)

In [19]:
df['Geom'].unique()


array([nan, '375358.612,4250802.750,547.769',
       '375355.532,4250801.982,547.634', '375356.721,4250802.920,547.426',
       '375356.760,4250802.927,547.429', '375356.125,4250804.675,547.252',
       '375356.116,4250804.686,547.248', '375361.279,4250801.179,547.767',
       '375361.221,4250801.320,547.761', '375360.719,4250801.322,547.003',
       '375360.723,4250801.326,547.004', '375360.820,4250801.712,547.396',
       '375361.554,4250801.076,547.654', '375357.628,4250804.002,546.395',
       '375357.634,4250804.002,546.396', '375357.533,4250804.033,546.371',
       '375357.556,4250804.075,546.364', '375357.893,4250804.418,546.263',
       '5357.926,4250804.013,546.379', '375354.958,4250803.556,546.377',
       '375354.957,4250803.556,546.377', '375354.749,4250803.467,546.160',
       '375354.759,4250803.468,546.161', '375355.027,4250803.400,545.840',
       '375354.654,4250803.855,545.948', '375355.668,4250803.337,545.821',
       '375355.018,4250803.412,545.846', '375353.868,425

In [23]:
df['D Code'].unique()

array([nan, 'SI-SIEVE', 'SP-SPECIAL_POTTERY', 'BP-BULK_POTTERY',
       'HR-HUMAN_REMAIN', 'SW-SPINDLEWHORL', 'GR-GROUND_SHOT',
       'FR-FAUNAL_REMAIN', 'WS-WORKED_STONE', 'LW-LOOM_WEIGHT',
       'FX-SEDIMENT_SAMPLE', 'HR-HUMAN_REMAINS',
       '"""""""BP-BULK_POTTERY"""""""""""""""'], dtype=object)

In [22]:
df['Id String'].unique()

array([nan, '20000', '20027', '20002', '20001', '20004', '20003', '20016',
       '20015', '20044', '20043', '20052', '20051', '20020', '20019',
       '20032', '20031', '20033', '20025', '20024', '20023', '20030',
       '20029', '20035', '20041', '20039', '20042', '20040', 'DUMMY2',
       '20014', '20008', '20013', '20007', '20045', '20046', '20055',
       '20049', '20050', '20064', '20063', 'unknown', 'DUMMY', '20036',
       '20037', '20038', '20057', '20056', '20059', '20060', '20071',
       '20075', '20072', '20088', '20086', '20079', '20087', '20074',
       '20061', '20068', '20062', '20066', '20082', '20067', '20090',
       '20081', '20092', '20080', '20094', '20093', '20058', '20089',
       '20073', '20104', '20096', '20095', '20069', '20070', '20085',
       '20077', '20076', '20097', '20103', '20102', '20138', '20133',
       '20139', '20132', '20107', '20108', '20123', '20124', '20145',
       '20128', '20135', '20112', '20006', '20109', '20110', '20115',
       '2011

In [24]:
df['Basket Barcode'].unique()

array([ nan])

In [25]:
df['Crate Number'].unique()

array([ nan,   2.,   3.,   1.,   5.,   7.,   9.,   4.,   8.,   6.,  10.])

In [26]:
df['Location'].unique()

array([ nan])

In [27]:
df['Square'].unique()

array([nan, '19-Jun', '19-Jul', '19-May', '5/19 and 6/19', '24-May', '0/0'], dtype=object)

In [28]:
df['Date'].unique()


array([nan, '7/23/2016', '7/29/2016', '7/25/2016', '7/26/2016',
       '7/28/2016', '7/30/2016', '8/2/2016', '7/31/2016', '8/3/2016',
       '8/1/2016'], dtype=object)

In [29]:
df['Total Count'].unique()

array([             nan,   4.26000000e+02,   3.10000000e+01,
         1.80000000e+01,   1.00000000e+00,   9.00000000e+00,
         2.00000000e+01,   4.20000000e+01,   4.00000000e+00,
         1.50000000e+01,   5.00000000e+00,   9.20000000e+01,
         2.90000000e+01,   3.00000000e+01,   6.00000000e+00,
         2.00000000e+00,   7.00000000e+01,   3.40000000e+01,
         1.10000000e+01,   3.30000000e+01,   4.40000000e+01,
         2.20000000e+01,   1.60000000e+01,   1.20000000e+01,
         6.80000000e+01,   2.60000000e+01,   8.00000000e+00,
         2.50000000e+01,   3.00000000e+00,   2.70000000e+01,
         1.30000000e+01,   2.30000000e+01,   7.70000000e+01,
         1.57000000e+02,   2.80000000e+01,   3.20000000e+01,
         0.00000000e+00,   8.30000000e+01,   3.60000000e+01,
         1.75000000e+02,   7.00000000e+00,   2.35700000e+03,
         2.05500000e+03,   2.04100000e+03,   2.41500000e+03,
         1.33000000e+02,   1.90000000e+01,   1.70000000e+01,
         2.95000000e+02,

In [30]:
df['Total Weight'].unique()

array([             nan,   2.30000000e-02,   5.54000000e-01,
         7.87000000e-01,   4.42000000e-01,   1.36000000e-01,
         7.33000000e-01,   1.15000000e-01,   2.64000000e-01,
         2.46000000e-01,   2.50000000e-01,   8.81000000e-01,
         8.39000000e-01,   8.00000000e-02,   5.29000000e-01,
         1.41000000e-01,   3.48000000e-01,   4.40000000e-02,
         2.70000000e-02,   5.36000000e-01,   2.27000000e-01,
         6.47000000e-01,   1.40000000e-02,   3.68000000e-01,
         7.02000000e-01,   5.94000000e-01,   3.30000000e-01,
         9.80000000e-02,   3.00000000e-03,   1.10000000e-01,
         7.80000000e-02,   1.42000000e-01,   1.88000000e-01,
         9.40000000e-01,   7.82000000e-01,   8.16000000e-01,
         1.70000000e+00,   3.20000000e-01,   1.76000000e-01,
         3.20000000e-02,   1.60000000e-01,   1.40000000e-01,
         3.70000000e-01,   2.31000000e-01,   3.90000000e-02,
         1.96000000e-01,   5.90000000e-02,   1.17000000e-01,
         1.80000000e-02,

In [31]:
df['Length'].unique()

array([ nan])

In [32]:
df['Width'].unique()

array([ nan])

In [33]:
df['Thickness'].unique()

array([ nan])

In [34]:
df['Kind'].unique()

array(['Excavation', nan, 'Pottery', 'Bone', 'Varia', 'Bead',
       'Ground Stone', 'Metal', 'Chemistry', 'Lithics', 'Figurine', 'Shell'], dtype=object)